### ISSUE TITLE
足りない記事・既存記事で移動すべき記事・その他修正

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb-docs#10]
## 足りない記事・既存記事で移動すべき記事

- [x] 運営者情報 `/server/profiles`
- [x] ガイドライン `/server/guidelines`
- [x] ガイドライン以下 `/server/guidelines/*`
- [x] プライバシーポリシー `/server/privacy`
- [x] お問い合わせ `/support/inquiry`
- [ ] 利用規約 `/server/terms`
  - 初期リリースでは無し、のちのち。利用規約部分はサーバルールリンクに置き換え

## その他修正

- [x] ディレクトリが存在する上位ファイルを下位ディレクトリに移動して `index.md` に名称変更
- [x] `/support/faq`
  - `もし、このページをご覧になっても問題が解決しない場合は公式Discordサーバの#questionなどで他の利用者に質問してみましょう！`
    - → `もし、このページをご覧になっても問題が解決しない場合は公式Discordサーバの#questionチャンネルなどで他の利用者に質問してみましょう！`
  - [x] 使用法 -> 使用方法
  - [x] 使用法コマンド部分のCodeタグ化

**Comment by Hiratake** [comment]
> 各種処罰方針: この場合にこういった処罰を行う・免責事項

「荒らし対策方針」みたいな名前のほうがそれっぽい感じないですかね？

**Comment by book000** [comment]
「荒らし」という言葉を使うことをあんまりしたくない…、荒らしにかかわらず「処罰を行う条件」とかも書くわけだし それぞれの処罰を行う方針について書かれた文書 = 「各種処罰方針」というわけでこれにしています

**Comment by Hiratake** [comment]
「処罰」より「荒らし対策」の方が、サーバを守るための施策をやってる感あって、前向きな感じするかなと思ったのだけども。
「処罰方針」だとなんとなく恐い感じあるのだけど、どうなんだろ

**Comment by book000** [comment]
そこに恐ろしさをもたらす必要あるかなあ…、もしやるなら「荒らし」という括りじゃなくてもうちょっと抽象的（迷惑行為全体をターゲットとするような）言葉のほうがいいかも

**Comment by Hiratake** [comment]
> 恐ろしさをもたらす必要あるかなあ

恐ろしさを感じさせないように「処罰方針」から名前を変えようって話。

> もうちょっと抽象的（迷惑行為全体をターゲットとするような）言葉のほうがいい

昨日色々調べてたんだけど思いつかなかったんだよなあ
コミュニティ防衛方針とか？

**Comment by book000** [comment]
あー逆に処罰方針自体が恐ろしい言葉だという認識ね…

**コミュニティ防衛方針**

**Comment by book000** [comment]
VCで案聞いた

- 処罰のねらい
- 禁止処置対応方針
- コミュニティ保守
- 「我々はなぜ処罰を執行するか」

**Comment by Hiratake** [comment]
**「我々はなぜ処罰を執行するか」**

中身の文章とタイトルに齟齬があったらよくないから、本文書いてみてから考えるってのもありかもしれん

**Comment by Hiratake** [comment]
コミュニティ防衛に関する方針とかコミュニティ保守方針とかだったら、権限関係の方針も入れちゃってよさそうみたいなとこあるよね

**Comment by book000** [comment]
コミュニティ保守方針ってもはやDiscordとかもひっくるめて全部になるんだよね

**Comment by book000** [comment]
利用規約以外とりあえず解決済みなのでクローズします
