### ISSUE TITLE
Limited Verifiedの定義を方針あたりに移動する

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb-docs#158]
ブログ記事だと流れてしまいやすいし、明確な定義としての固定ページがないのはよくないのでブログとは別にLimited Verifiedについてのページを作るべきかなあ

**Comment by Omuretsu** [comment]
「権限付与方針」にそのまま加えるにしては文量が多いよねえ

**Comment by Omuretsu** [comment]
`/server/policies/permissions/`（権限付与方針ページ）の直下にページを作成することは可能ですか？
可能ならば、`/server/policies/permissions/limitedverified/`みたいな形でページを作成するのが適切かなぁと思います。

**Comment by book000** [comment]
jaowebのpagesディレクトリ構造的に、 `_category/_subcategory/_slug` までしかいけないかも…。
https://github.com/jaoafa/jaoweb/blob/master/pages/_category/_subcategory/_slug.vue

**Comment by Omuretsu** [comment]
> ディレクトリ構造的に、 `_category/_subcategory/_slug` までしかいけないかも…。

🤔 

そうしたら、
・`/server/policies/`直下に作成。
・ただし`/server/policies/permissions/`として捉え、ナビゲーションバーなどにはリンクを掲載しない
（権限付与方針ページや、既存の`/blog/limited-verified`に「詳しくはこちら」という形でリンクを掲載する）

といった形になるでしょうか？

**Comment by book000** [comment]
ごちゃごちゃになるなあ…w
まあ技術的に「そうするしかない」という話になるのかしらね…

**Comment by Omuretsu** [comment]
> まあ技術的に「そうするしかない」という話になるのかしらね…

では、上記の方向で話を進めていきたいと思います。
今後また方向性が変わっても、すぐに修正できると思いますので。

**Comment by Omuretsu** [comment]
確認したいことがいくつかあるのですが

・新しく作るページは、従来のブログ記事から基本的にコピペでよいでしょうか
・従来のブロク記事は、固定ページの作成と引き換えに削除してもよいのでしょうか
（従来のブロク記事に向けたリンクは、切り替える必要あり）

**Comment by book000** [comment]
jaopediaとか各所のリンクをよく確認する必要性はありそうですが、まあソレでいいんじゃないでしょうか

**Comment by Omuretsu** [comment]
#184 を作成しましたので、よろしくお願いいたします。

**Comment by Omuretsu** [comment]
Mergeされたら、jaopediaおよびDiscordに記載されたリンクを最新のモノに更新する。

**Comment by Omuretsu** [comment]
Discordについては、過去のメッセージを編集することでページ移転を行った旨を告知。
（見る人がいるかわからんけど）

jaopediaについては、そもそも`Limited Verified`の説明が一切ありませんでした。
