### ISSUE TITLE
「Minecraftのアカウントが処罰された際、付随機能についても利用を制限する」旨の記述がない

### ISSUE THREAD

**Issue by Omuretsu** [jaoafa/jaoweb-docs#168]
### 対象の機能

jao Minecraft Server
Webサイトの記述内容

### 強化・改善の内容

表題のとおりです。
Discordのみ、Discordサーバ利用ルールにおいて以下のように定義されていました。
> jao Minecraft Serverの利用権利をなんらかの理由により失った場合、同時に公式Discordサーバの利用権利も失います。故に、その時点で利用者によって公式Discordサーバから退出しなければなりません。

**Comment by book000** [comment]
利用規約のような色々書けて全体適用可能なルールがないので(サーバルールは基本的な部分以外の細かいことを書きたくない)、分離している各所に書くしかない気がします
もしくは諦めて利用規約を作り直すか。
