### ISSUE TITLE
「Discordサーバルール」ページのタイトル変更の提案

### ISSUE THREAD

**Issue by Omuretsu** [jaoafa/jaoweb-docs#173]
### 対象の機能

「Discordサーバルール」
https://jaoafa.com/server/rules/discord

### 強化・改善の内容

現在の表記だと「Discord（大元）の利用ルール」だと捉えられる可能性があると感じました。
「jMS Discordサーバルール」と表記するなど、「"jao Minecraft Server"が運営するコミュニティ内で適用されるルール」であることを、タイトルの部分で明確にすることを提案します。

**Comment by book000** [comment]
私は#infoとか色々なところで「公式Discordサーバ」という表現を多用しています。
これも開発元の公式とも捉えられる可能性があるので、どうしたものですかね

**Comment by book000** [comment]
ただ、「Discordルール」ではなく「Discord**サーバ**ルール」なので誤認するなって本文で明記すれば十分な気もするんですけどね…

**Comment by Omuretsu** [comment]
> ただ、「Discordルール」ではなく「Discordサーバルール」なので誤認するなって本文で明記すれば十分な気もするんですけどね…

現状、当該ページ内の説明が以下のモノしかないので、最低でも本文中に「開発元の規約とは別物」という旨は追記したほうがよいと思われます。
> このページでは、jao Minecraft Serverの公式Discordサーバである「jMS Gamers Club」（以下、「公式Discordサーバ」と呼びます）におけるルール・方針について記載します。
> なおこのページでの「運営」とは、 jao Minecraft Server での運営スタッフのことを指します。
