### ISSUE TITLE
「鉄道・道路敷設に関するガイドライン」の改定

### ISSUE THREAD

**Issue by Omuretsu** [jaoafa/jaoweb-docs#179]
[鉄道・道路敷設に関するガイドライン](https://jaoafa.com/server/guidelines/railways) について、以下を追記する必要があります。

・方針を定めている理由（そもそもの運営の見解や、鉄道に関する嫌悪感）
・鉄道施設などに、サーバの運営が運用していると誤解されるような名称を使わない（中央駅など）

**Comment by book000** [comment]
どうせあのスレッドまともに動かない気がするので、草案立てて意見文句受け付ける形しかまともに進まない気がするんですけどね。

純粋に以下の変更をかければとりあえずはよさそうです

- 「基本方針」に「他の利用者が運営の管理物であると誤認するような名称を使用しないこと」の追加（jaoweb上では運営を `運営チーム` と統一している可能性があるので要確認）
- 「ガイドラインの制定理由」項目を追加

## ガイドラインの制定理由について

※適当に書いたので加筆修正ください。アスタリスクがついている項目は確認・修正が必要。長々書くことについてもよくわかんねーね

jao Minecraft Server には、過去に起きた鉄道絡みのトラブルにより「鉄道」そのものについての嫌悪感\*1があります。
そのトラブルは「鉄道が好きで好きで堪らない人」が他の自治体管理者やプレイヤーの意見を尊重せずに勝手にサーバ内の各所に鉄道を通したり、既存の鉄道を改変したり、他の人が作った鉄道に対して文句をつけたりといったものでした。これが複数回起き、鉄道そのものに対して運営や常連メンバーの多くがあまり好意的に見ることができなくなってしまいました。\*2

そのトラブルがあって以降、数年間の間「運営への許可のない鉄道敷設・管理の完全禁止措置」が行われていたのですが、多くのプレイヤーの方々が jao Minecraft Server に来られる中で「鉄道についてもう少し制限を緩くしても良いのではないか」という意見が多くあり、現在の「ガイドライン」という形で鉄道について取り決めがなされています。

今でこそ運営の承認なく鉄道を敷設することができるようになりましたが、運営や常連メンバーが鉄道そのものに対して持つ嫌悪感\*1は変わっていません。
もしこのサーバで鉄道を敷設したいと思うのであれば、jao Minecraft Server の雰囲気をよく知り、多くのプレイヤーの方と交流してから少しづつ取り組むことをお勧めします。

- *1: 嫌悪感という言葉が微妙に正しくない気がします。「あんまり良く思ってない」的なニュアンスなんだけどなんだろうね
- *2: リアルの「鉄オタ」に対する不信感・嫌悪感を含む

**Comment by Omuretsu** [comment]
> どうせあのスレッドまともに動かない気がするので、草案立てて意見文句受け付ける形しかまともに進まない気がするんですけどね。

そうですね。ただし議論の進行方法については、検討の余地がありそうです。
（スレッドにて議論し議決を取ってからPRを立てるのか、それともある程度PRをもとに議論を取ってから議決を取るのか、など）

**Comment by book000** [comment]
まあ…本当は前者が正しいですけど進まないものはなあって感じです
文章作ってこれでどうですか？意見があればくださいスタイルが結局話が進むんですよね

**Comment by yuuahp** [comment]
> *2: リアルの「鉄オタ」に対する不信感・嫌悪感を含む  

は、ガイドラインやその制定理由の趣旨から外れている気がします。

**Comment by book000** [comment]
アスタリスクの項目はあくまでこのissueでの文章への注釈なので採用する文章に入れるわけではないです。
ただまあ、わざわざ書かなくてもよかったかも…

**Comment by Omuretsu** [comment]
これ以降の議論は　#181 にてお願いいたします。
