### ISSUE TITLE
既存のブログ記事のうちアクセス数の多いものを移す

### ISSUE THREAD

**Issue by Hiratake** [jaoafa/jaoweb-docs#18]
現在公開されているブログ記事のうち、アクセス数が多いものを移す。

**Comment by Hiratake** [comment]
アクセス多いのはこのへん
https://jaoafa.com/blog/tomachi/discord_username
https://jaoafa.com/blog/minhero_exp/new_skinchange

2段階認証の記事はアカウント乗っ取りの件があったので設定してもらうために移したさある
https://jaoafa.com/blog/minhero_exp/discord_security

みんなWEつかうから解説記事は情報更新して移したい（WEわからん）
https://jaoafa.com/blog/minhero_exp/worldedit_commentary

**Comment by book000** [comment]
- `tomachi/discord_username`: https://github.com/jaoafa/jaoweb-docs/blob/blog-contents/blog/discord-username.md
- `minhero_exp/new_skinchange`: https://github.com/jaoafa/jaoweb-docs/blob/blog-contents/blog/skin-change.md
- `minhero_exp/discord_security`: [discord-2-factor.md](https://github.com/jaoafa/jaoweb-docs/files/6303966/discord-2-factor.md) (画像とかstorageに移さないとならないかも…)
- `minhero_exp/worldedit_commentary`: https://github.com/jaoafa/jaoweb-docs/blob/blog-contents/blog/worldedit_commentary.md

## ついでに

- WECUIの使い方(Fabricのためにリライトの必要あり): https://github.com/jaoafa/jaoweb-docs/blob/blog-contents/blog/worldeditcui_commentary.md
- WGの利用解説: https://github.com/jaoafa/jaoweb-docs/blob/blog-contents/blog/worldguard_commentary.md
