### ISSUE TITLE
変更が反映されない

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/jaoweb-docs#28]
[ここらへん以降](https://github.com/jaoafa/jaoweb-docs/commit/30b46f8356aad22fbdab3212e629f692867b024f)の変更が本サイトの方に反映されていないようです。jaoweb.tomacheeseの方には反映されています。
![jftm](https://user-images.githubusercontent.com/75877469/115019633-6d6cfc80-9ef4-11eb-82cc-c28d0c5c2fda.PNG)

**Comment by Hiratake** [comment]
> 直しました…

圧倒的感謝🙏

> 本件は jaoafa/jaoweb-docs に関連した事項であると考えるため、移動します。

たしかに

**Comment by book000** [comment]
訂正。

普通の「プッシュ」では、タグの反映がなされないので以下の方法でプッシュしてください

1. VSCodeで `F1` を押してコマンド入力画面を開く
2. `git tag` と入力する
3. `Git: タグをプッシュ` (または `Git: Push Tags`) という項目があるので、これをクリック
4. GitHub上で追加したタグが反映されていることを確認

![](https://i.imgur.com/YFJBUPo.png)

**Comment by minhero-exp** [comment]
圧倒的感謝🙏

**Comment by book000** [comment]
解決したものとしてクローズします
