### ISSUE TITLE
ホームページ右上のカテゴリ的分類にリンクしようとしている箇所があり、そこを押すと404になる

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb-docs#76]
例：サーバ情報カテゴリの「はじめての方へ」ページの左上にあるサイトマップ的なあれの「サーバ情報」を押すと404。
その他にもお問い合わせカテゴリの「よくあるご質問」ページの左上の「お問い合わせ」を押すと404。
![image](https://user-images.githubusercontent.com/52349485/133730570-4d12f15f-753e-425e-be22-bd682c2553a7.png)

**Comment by Hiratake** [comment]
docs側だと思うので移します。

**Comment by Hiratake** [comment]
「サーバ情報」に関しては jaoafa/jaoweb-docs#75 で対応中です。

**Comment by book000** [comment]
> その他にもお問い合わせカテゴリの「よくあるご質問」ページの左上の「お問い合わせ」を押すと404。

`support/index.md` を作る必要がありそうです。

**Comment by Hiratake** [comment]
たしかに
