### ISSUE TITLE
Minecraft-Discordリンク解除後、再リンクした場合の権限復元について ※承認済

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb-docs#88]
現行のルール及び方針ではlinkが最終ログインから3ヶ月経過によって自動的に解除され(3month)たあと、再度リンクした場合の権限復元について明文化されていません。
数日前の更新で、サブアカウントと紐ついているメインアカウントがサーバから退出した場合、1ヶ月後にサブアカウント連携を解除し結果としてキックされるルールが施行されています。https://github.com/jaoafa/jaoweb-docs/pull/71

これに合わせ、~~最終ログインから3ヶ月経過したことによってlinkが解除されDefault権限に戻った場合、解除されてから1ヶ月以内であれば権限を自動または手動で復元する~~ **「権限戻っても、申請があれば運営の判断で復元する」** という形で明文化・運用したら良いのではと考えるのですが、いかがでしょうか？
なお、このissueである程度決まったら運営内審議に上げ、承認されたらルールに反映します。

**Comment by Hiratake** [comment]
1ヶ月すぎてても、運営の判断で戻すか～ってなりそうだから、「権限戻っても、申請があれば運営の判断で復元する」的なのにしてもイイン・ジェーン

**Comment by book000** [comment]
自動化もしない？

**Comment by Hiratake** [comment]
権限が戻ってしまって、もとに戻すケースってRくらいでしょ
そんな数も多くないんだし、3ヶ月離れてたんなら常連と呼べなくなってることだってあるから自動化はできないでしょ

**Comment by Hiratake** [comment]
たぶん

**Comment by book000** [comment]
なるほどね、じゃあまあたしかに「権限戻っても、申請があれば運営の判断で復元する」を明文化したほうがよさそう

**Comment by Omuretsu** [comment]
「3ヶ月の失効後1週間以内にlinkすれば、自動で再付与」
「3ヶ月+1週間 以降は運営の判断で手動付与」
でどう？

実際忘れててlink失効とかもありそうだし、それに伴う申請をいちいち処理するもの面倒じゃない？

> 3ヶ月離れてたんなら常連と呼べなくなってることだってあるから自動化はできないでしょ
CRは今4人しかいないけど、そういう人ってマイクラ鯖にはあまり来ないから、そういう人向けの対策として自動再付与はあったほうがよさそう。

**Comment by book000** [comment]
以下の内容で承認されました:

```
現行のシステム運用形態では、
1. 最終ログインから3ヶ月経過後linkを自動切断、Regular以下は自動でDefault権限に変更
2. その後再リンクした場合、元Regularユーザーに限っては運営メンバー側で必要に応じて権限を手動付与
という、明文化されていない2の考え方があります
本審議では、これを解決するために以下の明文化を行い、ルールに反映させることについての賛成・反対の決を採ります。

・3ヶ月経過後に自動切断され、その後1週間以内に再リンクした場合は自動的に権限を復元
・1週間後以降は当人による申請・運営の判断により権限を復元
・権限の復元は自動切断から1ヶ月以内とし、以降の復元は認めない。
・Admin・Moderatorについても自動リンク解除から1ヶ月以内に再接続しない場合はAdmin・Moderatorからの脱退を求める (このケースについては運営内で臨機応変に対応する)
追: すべてのlink解除処理は事前に#supportにて申請を行うことで延期可能
```

該当ページへの反映を随時行いたいのですが、私がその時間をとれるか微妙なのでお時間がある人がいたらプルリクください
