### ISSUE TITLE
ブログ記事を本当に移行する必要があるのか？

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb-docs#9]
表題通り

新Webサイトにする場合に、何でもかんでも全てのブログ記事を持ってくることが正解なのかどうか疑問点があります。  
正直まっさらで初めてもいいんじゃないかと思わんくもなかったり…。

PV数取れてる記事とかは作ってもいいかもだけど、記事内容がもはや過去の遺物のような記事とかを持ってきてもなあ…と思わないこともない。あとTextLintかけるとほぼほぼエラーを出す。つらい。

**Comment by minhero-exp** [comment]
過去の出来事を知ってもらうために～とも考えたけど、jaopediaとかサーバの歴史ページもあるしまっさらでも良いのかもしれない。Mod・プラグインとかの解説記事は欲しい

**Comment by book000** [comment]
@Hiratake

**Comment by book000** [comment]
どこかのタイミングで現時点のブログ記事を残したブランチを作って、mainブランチからblogディレクトリ以下を削除します。

**Comment by book000** [comment]
クローズまでしなくてもいいや
